---
- name: Configure Web Servers with Nginx and Deploy AI Website
  hosts: webservers
  become: yes

  vars:
    app_root_dir: "/var/www/ai_website" 
    document_root_dir: "{{ app_root_dir }}/html"

  tasks:
    - name: Обновить кэш apt и установить NGINX
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Создать корневые директории для сайта
      ansible.builtin.file:
        path: "{{ document_root_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      when: app_root_dir is defined and document_root_dir is defined

    - name: Копировать файлы сайта на сервер
      copy:
        src: "{{ playbook_dir }}/site_content/"
        dest: "{{ document_root_dir }}/"
        owner: www-data
        group: www-data
        mode: '0644'
      when: document_root_dir is defined

    - name: Применить шаблон конфигурации NGINX
      template:
        src: "{{ playbook_dir }}/ansible_templates/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/default"
        owner: root
        group: root
        mode: '0644'
      notify: Перезапустить NGINX
      when: document_root_dir is defined

    - name: Убедиться, что новый сайт включен (создать симлинк)
      file:
        src: "/etc/nginx/sites-available/default"
        dest: "/etc/nginx/sites-enabled/default"
        state: link
        force: yes
      notify: Перезапустить NGINX

    - name: Удалить дефолтную конфигурацию Nginx (если она есть)
      file:
        path: "/etc/nginx/sites-enabled/default_nginx.conf"
        state: absent
      notify: Перезапустить NGINX
      ignore_errors: yes

    - name: Запустить службу NGINX (убедиться, что она работает)
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Проверить статус службы NGINX
      command: systemctl status nginx
      register: nginx_status
      changed_when: false

    - name: Вывести статус NGINX
      debug:
        msg: "{{ nginx_status.stdout_lines }}"

  handlers:
    - name: Перезапустить NGINX
      service:
        name: nginx
        state: restarted
